export const MATERIAL_ROOM_OPTIONS: string[] = [
  'Área de Serviço',
  'Área Externa',
  'Área Gourmet',
  'Banheiro',
  'Closet',
  'Cozinha',
  'Despensa',
  'Escritório',
  'Garagem',
  'Hall de Entrada',
  'Lavabo',
  'Quarto',
  'Recepção',
  'Sala de Estar',
  'Sala de Jantar',
  'Sala de Reunião',
  'Suíte',
  'Varanda',
]
